import { CardParams } from '@/components/mycard';

export const getFakeCardData = (): CardParams[] => {
  return [
    // From College to Station
    {
      id: '1',
      name: 'John D.',
      destination: 'Station',
      date: new Date('2025-10-20T08:30:00'),
      from: 'College',
    },
    {
      id: '2',
      name: 'Jane S.',
      destination: 'Station',
      date: new Date('2025-10-21T09:00:00'),
      from: 'College',
    },
    {
      id: '3',
      name: 'Mike J.',
      destination: 'Station',
      date: new Date('2025-10-22T09:15:00'),
      from: 'College',
    },
    {
      id: '4',
      name: 'Sarah W.',
      destination: 'Station',
      date: new Date('2025-10-20T10:00:00'),
      from: 'College',
    },
    {
      id: '5',
      name: 'Chris L.',
      destination: 'Station',
      date: new Date('2025-10-21T10:45:00'),
      from: 'College',
    },
    {
      id: '6',
      name: 'Emily B.',
      destination: 'Station',
      date: new Date('2025-10-22T11:30:00'),
      from: 'College',
    },
    {
      id: '7',
      name: 'David M.',
      destination: 'Station',
      date: new Date('2025-10-20T12:00:00'),
      from: 'College',
    },

    // From College to Airport
    {
      id: '8',
      name: 'Laura G.',
      destination: 'Airport',
      date: new Date('2025-10-21T12:20:00'),
      from: 'College',
    },
    {
      id: '9',
      name: 'James R.',
      destination: 'Airport',
      date: new Date('2025-10-22T13:00:00'),
      from: 'College',
    },
    {
      id: '10',
      name: 'Linda H.',
      destination: 'Airport',
      date: new Date('2025-10-20T13:45:00'),
      from: 'College',
    },
    {
      id: '11',
      name: 'Robert M.',
      destination: 'Airport',
      date: new Date('2025-10-21T14:30:00'),
      from: 'College',
    },
    {
      id: '12',
      name: 'Patricia T.',
      destination: 'Airport',
      date: new Date('2025-10-22T15:00:00'),
      from: 'College',
    },
    {
      id: '13',
      name: 'Michael A.',
      destination: 'Airport',
      date: new Date('2025-10-20T15:15:00'),
      from: 'College',
    },
    {
      id: '14',
      name: 'Barbara T.',
      destination: 'Airport',
      date: new Date('2025-10-21T16:00:00'),
      from: 'College',
    },

    // From Station to College
    {
      id: '15',
      name: 'William J.',
      destination: 'College',
      date: new Date('2025-10-22T16:45:00'),
      from: 'Station',
    },
    {
      id: '16',
      name: 'Elizabeth W.',
      destination: 'College',
      date: new Date('2025-10-20T17:30:00'),
      from: 'Station',
    },
    {
      id: '17',
      name: 'Richard H.',
      destination: 'College',
      date: new Date('2025-10-21T18:00:00'),
      from: 'Station',
    },
    {
      id: '18',
      name: 'Jennifer M.',
      destination: 'College',
      date: new Date('2025-10-22T18:20:00'),
      from: 'Station',
    },
    {
      id: '19',
      name: 'Charles T.',
      destination: 'College',
      date: new Date('2025-10-20T19:00:00'),
      from: 'Station',
    },
    {
      id: '20',
      name: 'Susan G.',
      destination: 'College',
      date: new Date('2025-10-21T19:45:00'),
      from: 'Station',
    },
    {
      id: '21',
      name: 'Joseph M.',
      destination: 'College',
      date: new Date('2025-10-22T20:30:00'),
      from: 'Station',
    },

    // From Airport to College
    {
      id: '22',
      name: 'Margaret R.',
      destination: 'College',
      date: new Date('2025-10-20T21:00:00'),
      from: 'Airport',
    },
    {
      id: '23',
      name: 'Thomas C.',
      destination: 'College',
      date: new Date('2025-10-21T21:15:00'),
      from: 'Airport',
    },
    {
      id: '24',
      name: 'Dorothy R.',
      destination: 'College',
      date: new Date('2025-10-22T22:00:00'),
      from: 'Airport',
    },
    {
      id: '25',
      name: 'Daniel L.',
      destination: 'College',
      date: new Date('2025-10-20T22:45:00'),
      from: 'Airport',
    },
    {
      id: '26',
      name: 'Karen L.',
      destination: 'College',
      date: new Date('2025-10-21T23:30:00'),
      from: 'Airport',
    },
    {
      id: '27',
      name: 'Paul W.',
      destination: 'College',
      date: new Date('2025-10-22T07:00:00'),
      from: 'Airport',
    },
    {
      id: '28',
      name: 'Nancy H.',
      destination: 'College',
      date: new Date('2025-10-20T07:20:00'),
      from: 'Airport',
    },
    {
      id: '29',
      name: 'Mark A.',
      destination: 'College',
      date: new Date('2025-10-21T08:00:00'),
      from: 'Airport',
    },
    {
      id: '30',
      name: 'Betty Y.',
      destination: 'College',
      date: new Date('2025-10-22T08:15:00'),
      from: 'Airport',
    },
  ];
};
